#!/usr/bin/env bash
if [ ! -f .env ]; then
    echo "ERROR: need to create .env from .env.dist"
    exit
fi

set -ex

source ./.env
export $(cut -s -d= -f1 ./.env)
DOCKER_PROJECT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

echo 'project initialized'