#!/usr/bin/env bash
if [ ! -f .env ]; then
    echo "ERROR: need to create .env from .env.dist"
    exit
fi

set -ex

source ./.env
export $(cut -s -d= -f1 ./.env)
DOCKER_PROJECT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# for Mutagen installation: Update Magento path in mutagen.yml
sed -ie "s|alpha: .*|alpha: \"$MAGENTO_PATH\"|" $DOCKER_PROJECT_DIR/mutagen.yml

cd $MAGENTO_PATH

echo 'project initialized'