#!/bin/bash
shopt -s extglob

source /tmp/.env
#cp /var/www/magento-docker/etc/php/tools/* /usr/local/sbin

sleep 60

#clean project dir
rm -rf generated/* var/* app/etc/env.php app/etc/config.php

echo "$(date +"%T") Magento 2 Installation START"

cd /var/www/magento2ce

#install magento
composer install
bin/magento setup:install \
   --cleanup-database \
   --backend-frontname=admin \
   --admin-lastname=Admin \
   --admin-firstname=Admin \
   --admin-email=admin@magento.test \
   --base-url=https://magento.test/ \
   --admin-user=${ADMIN_USER} \
   --admin-password=${ADMIN_PASSWORD} \
   --db-name=magento \
   --db-host=db \
   --elasticsearch-host=elastic \
   --db-prefix=

echo "Compiling Magento with changes..."
bin/magento setup:upgrade
bin/magento setup:di:compile
bin/magento cache:flush

# apply Magento configs
bin/magento config:set web/secure/base_url https://magento.test/

echo "Magento 2 Successfully installed!"
echo "To open it navigate to https://magento.test/"

echo "$(date +"%T") Magento 2 Installation END"
