#!/usr/bin/env bash

sleep 30

#clean project dir
rm -rf generated/* var/* app/etc/env.php app/etc/config.php

echo "$(date +"%T") Magento 2 Installation START"

cd /var/www/magento2ce

#install magento
composer install
bin/magento setup:install \
   --backend-frontname=admin \
   --admin-lastname=Admin \
   --admin-firstname=Admin \
   --admin-email=admin@magento.test \
   --base-url=https://magento.test/ \
   --admin-user=${ADMIN_USER} \
   --admin-password=${ADMIN_PASSWORD} \
   --cleanup-database \
   --db-host=db --db-name=magento --db-prefix= \
   --search-engine="opensearch" \
   --opensearch-host=elastic --opensearch-port=${ELASTIC_PORT} \
   --elasticsearch-host=elastic --elasticsearch-port=${ELASTIC_PORT} \

echo "Compiling Magento with changes..."
bin/magento setup:upgrade
bin/magento setup:di:compile
bin/magento cache:flush

# apply Magento configs
bin/magento config:set web/secure/base_url https://magento.test/

echo "Magento 2 Successfully installed!"
echo "To open it navigate to https://magento.test/"

echo "$(date +"%T") Magento 2 Installation END"
