#!/usr/bin/env bash

# If you want to add custom dependencies before installation you can use this file for that.

echo "Starting execution of custom pre-scripts!"

# composer require opensearch-project/opensearch-php:2.0.0
# composer update

echo "Custom pre-scripts completed successfully!"
