#!/usr/bin/env bash

bin/magento cache:flush

php -d memory_limit=-1 -f bin/magento setup:performance:generate-fixtures -s setup/performance-toolkit/profiles/${MAGENTO_EDITION}/${MAGENTO_PROFILE}.xml

sleep 30

php -d memory_limit=-1 -f bin/magento indexer:reindex

bin/magento cache:flush