#!/usr/bin/env bash

php -d memory_limit=-1 -f bin/magento setup:performance:generate-fixtures -s setup/performance-toolkit/profiles/${PROFILE_EDITION}/${PROFILE_SIZE}.xml

bin/magento cache:flush

sleep 30

php -d memory_limit=-1 -f bin/magento indexer:reindex

bin/magento cache:flush